apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: kafka-deployment
  ports:
  - protocol: TCP
    name: port1
    port: 9092
    targetPort: 9092
  - protocol: TCP
    name: port2
    port: 29092
    targetPort: 29092

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-deployment
  name: kafka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-deployment
  template:
    metadata:
      labels:
        app: kafka-deployment
    spec:
      containers:
      - env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-service:2181
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: PLAINTEXT_INTERNAL
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka-service:29092
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT, PLAINTEXT_INTERNAL:PLAINTEXT
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        image: confluentinc/cp-kafka:7.3.3
        imagePullPolicy: IfNotPresent
        name: kafka-service
        ports:
        - containerPort: 9092
        - containerPort: 29092
